# Your name and what you do
name: Metedev0
bio: Software Developer

description: Mete's Personal Website

# Profile picture
picture: assets/images/profile.jpg

# your url: http://metedev0.github.io
url: https://metedev0.github.io

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
twitter: metedev0
linkedin: #
github: metedev0
email: meteyilma@proton.me
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - HTML, Jade
    - CSS (Stylus, Sass, Less)
    - Javascript, NodeJS
    - AngularJS, ReactJS
    - Java, Android
    - Python
    - Git

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    Ksozluk:
        name: Ksozluk
        description: Personal Turkish dictionary.
        url: https://ksozluk.github.io
    MemeCommunity:
        name: MemeCommunity
        description: Funny meme template community.
        url: https://memecommunity.netlify.app
    Codespot:
        name: Codespot
        description: Codespot web application.
        url: https://github.com/metedev0/codespot

# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
    - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
